# This file was generated by GoReleaser. DO NOT EDIT.
cask "syllable" do
  version "1.7.1"

  on_macos do
    on_intel do
      sha256 "1b1539dc3bed97eb1345cf1da016cda711e9cb69a5fc5df07b15d8278dbe2487"
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
    end
    on_arm do
      sha256 "5b22ec97841eebc6eb22ec253e98c901594e1962f518ef2c48ed6cd3a05bf3d8"
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "e12e00a9a3a020c9aad9ed8fb83cfde03b22c39a62ffd6be191ac9e764133a87"
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_linux_amd64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
    end
    on_arm do
      sha256 "779594bffb6eed89b5a27fb91cde538d18f66b3336a0ca44df96542dedbf74cf"
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_linux_arm64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
    end
  end

  name "syllable"
  desc "CLI for the Syllable AI platform"
  homepage "https://github.com/asksyllable/syllable-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "syllable"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/syllable"]
    end
  end

  # No zap stanza required

end
