# This file was generated by GoReleaser. DO NOT EDIT.
cask "syllable" do
  version "1.4.0"

  on_macos do
    on_intel do
      sha256 "487997243e3397d9bdbe2cc9717f6afe9b9cd79263786b80386fc9462cafdbf0"
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
    end
    on_arm do
      sha256 "52e605fd97479cbca4a3af825ead053e8a35fac840dbb14056596259574c2b08"
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
    end
  end

  on_linux do
    on_intel do
      sha256 "abd2b4e839b7207d70d26405c96cae93b40fde34cf0a6fcd64c75bd67ef6b7d0"
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_linux_amd64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
    end
    on_arm do
      sha256 "15aee73bd223cb062b35a6a672b8435714df82910e92d35aaaebe94fd30effb4"
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_linux_arm64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
    end
  end

  name "syllable"
  desc "CLI for the Syllable AI platform"
  homepage "https://github.com/asksyllable/syllable-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "syllable"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/syllable"]
    end
  end

  # No zap stanza required

end
