# This file was generated by GoReleaser. DO NOT EDIT.
cask "syllable" do
  name "syllable"
  desc "CLI for the Syllable AI platform"
  homepage "https://github.com/asksyllable/syllable-cli"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "syllable"

  on_macos do
    on_intel do
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
      sha256 "0baecfb55f643e4078cf7b7dd02c969a58c4f6deda7c9d5b5e630ed7b9b8bd58"
    end
    on_arm do
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
      sha256 "d9c87608c7ca787a3bea0a8b879b9a559ec3c1e0516fcd087d621fa78a659c9a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_linux_amd64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
      sha256 "d93257a213f077bee5377c96f74510e363bb5b7afae126a8e73185b8aec2761f"
    end
    on_arm do
      url "https://github.com/asksyllable/syllable-cli/releases/download/v#{version}/syllable_#{version}_linux_arm64.tar.gz",
        verified: "github.com/asksyllable/syllable-cli"
      sha256 "a7026f3ad78be89e2e3f1646c8ea3284074d567a914588c704c43be29aca0ff2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/syllable"]
    end
  end

  # No zap stanza required
end
